kind: Deployment
apiVersion: apps/v1
metadata:
  name: abctechnologies-dep
spec:
  replicas: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: abc-tech-app
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
        - name: app
          image: asue1/abctechnologies:v1
---
kind: Service
apiVersion: v1
metadata:
  name: abc-tech-service
spec:
  type: NodePort
  selector:
    app: abc-tech-app
  ports:
    - port: 89           # Cluster port
      targetPort: 8090   # Container port
      nodePort: 32000    # Optional: specify a NodePort
